---
apiVersion: v1
kind: Namespace
metadata:
  name: kubearmor
  labels:
      aws.conformance.vendor: accuknox
      aws.conformance.vendor-solution: kubearmor
      aws.conformance.vendor-solution-version: "v1.3.2"
